// Taylor Snyder, Cameron Wandfluh
// Mizzou 2017 - Fall

var affixes = 
[
  "Blindness",
  "Bravery",
  "Burning",
  "Burrowing",
  "Conjuration",
  "Darkness",
  "Dawn",
  "Death",
  "Deception",
  "Defense",
  "Deflection",
  "Delerium",
  "Desire",
  "Despair",
  "Destruction",
  "Domination",
  "Doom",
  "Dragonslaying",
  "Dreaming",
  "Durability",
  "Dusk",
  "Evocation",
  "Fire",
  "Flame",
  "Freezing",
  "Fury",
  "Glory",
  "Growth",
  "Healing",
  "Heroism",
  "Hope",
  "Horror",
  "Ice",
  "Illusion",
  "Impact",
  "Imprisonment",
  "Incineration",
  "Insanity",
  "Invulnerability",
  "Invisibility",
  "Justice",
  "Life",
  "Light",
  "Lightlessness",
  "Lightning",
  "Love",
  "Madness",
  "Malice",
  "Mercy",
  "Midnight",
  "Obedience",
  "Peace",
  "Petrification",
  "Piercing",
  "Planeswalking",
  "Prophecy",
  "Rage",
  "Resurrection",
  "Retribution",
  "Seeking",
  "Shadow",
  "Shadowbinding",
  "Shattering",
  "Shieldbreaking",
  "Shielding",
  "Shocking",
  "Siege",
  "Sightblinding",
  "Silence",
  "Smiting",
  "Solidity",
  "Soul",
  "Soulbinding",
  "Soulcutting",
  "Spellbreaking",
  "Starlight",
  "Stealth",
  "Stonecutting",
  "Striking",
  "Sundering",
  "the Angel",
  "the Banshee",
  "the Centaur",
  "the Demon",
  "the Desert",
  "the Dragon",
  "the Dwarf",
  "the Elf",
  "the Elements",
  "the Fairie",
  "the Gargoyle",
  "the Genie",
  "the Ghost",
  "the Ghoul",
  "the Giant",
  "the Gnome",
  "the Goblin",
  "the God",
  "the Gremlin",
  "the Gryphon",
  "the Homunculus",
  "the Lich",
  "the Mermaid",
  "the Monster",
  "the Ogre",
  "the Orc",
  "the Titan",
  "the Troll",
  "the Vampire",
  "the Werebeast",
  "the Werewolf",
  "the Wight",
  "Thought",
  "Townsaving",
  "Treachery",
  "True Sight",
  "Twilight",
  "Valor",
  "Vengeance",
  "Void",
  "Warding",
  "Wayfinding",
  "Weightlessness",
  "Wind",
  "Winter",
  "Wisdom",
  "Woundhealing",
];

var prefixes = 
[
    "Tasteful", 
    "Inquisitive", 
    "Peaceful", 
    "Earsplitting", 
    "Envious", 
    "Encouraging", 
    "Zonked", 
    "Hollow", 
    "Troubled", 
    "Dead", 
    "Royal", 
    "Parsimonious", 
    "Ajar", 
    "Billowy", 
    "Oval", 
    "Acidic", 
    "Hilarious", 
    "Expensive", 
    "Deafening", 
    "Wealthy", 
    "Hot", 
    "Deserted", 
    "Nondescript", 
    "Abundant", 
    "Magical", 
    "Able", 
    "Honorable", 
    "Inexpensive", 
    "Rich", 
    "Useful", 
    "Orange", 
    "Undesirable", 
    "Polite", 
    "Protective", 
    "Aquatic", 
    "Future", 
    "Overwrought", 
    "Whimsical", 
    "Dashing", 
    "Periodic", 
    "Maniacal", 
    "Gruesome", 
    "Capable", 
    "Sweltering", 
    "Square", 
    "Alluring", 
    "Materialistic", 
    "Scattered", 
    "Late", 
    "Dry", 
    "Foolish", 
    "Steadfast", 
    "Classy", 
    "Gray", 
    "Comfortable", 
    "Imported", 
    "Creepy", 
    "Brown", 
    "Shallow", 
    "Separate", 
    "Hateful", 
    "Endurable", 
    "Faint", 
    "Rustic", 
    "Miscreant", 
    "Dynamic", 
    "Attractive", 
    "Recondite", 
    "Dangerous", 
    "Shiny", 
    "Dirty", 
    "Bashful", 
    "Glamorous", 
    "Uttermost", 
    "Annoying", 
    "Smiling", 
    "Alcoholic", 
    "Scared", 
    "Shrill", 
    "Flaky", 
]

function GenerateItemName(itemType)
{
    var affix = affixes[Math.floor(Math.random() * affixes.length)];
    var prefix = prefixes[Math.floor(Math.random() * prefixes.length)];
    
    var itemName = prefix + " " + itemType + " of " + affix;
    
    return itemName;
}
 
